print("hello world , first time i am going to push that repo. in github")
print("this line is added from github")
print("third line is also from github")
print("hey this is dev2 branch from github")
print("do some fetch operation")
print("do some commit else it take default commit 'update'")
print("i imoprot somethign")
